nginx:
  build: nginx
  links:
    - app
  ports:
    - "80:80"

app:
  build: src
  links:
    - db
  expose:
    - "3000"
  # adding ports : - 3000:3000 exposes this to public

db:
  build: db
  volumes:
    - /data/mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=test
