nginx:
  build: nginx
  links:
    - app
  ports:
    - "80:3000"

app:
  build: src
  links:
    - db

db:
  build: db
  volumes:
    - /data/mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=test
