nginx:
  extends:
    file: docker-common.yml
    service: nginx
  links:
    - webapp

webapp:
  extends:
    file: docker-common.yml
    service: webapp
  links:
    - db
  volumes:
    - ./webapp:/webapp
  environment:
    - VIRTUAL_HOST=leaguewinspool.docker # for https://github.com/codekitchen/dinghy#optional-http-proxy
    - NODE_ENV=development

db:
  extends:
    file: docker-common.yml
    service: db
  volumes_from:
    - dbdata

dbdata:
  extends:
    file: docker-common.yml
    service: dbdata
