nginx:
  build: nginx
  links:
    - app
  ports:
    - "80:80"

app:
  build: app
  links:
    - db
  expose:
    - "3000"

db:
  build: db
  volumes:
    - /data/mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=test
